

export const sample_foods: any[] = [
    {
      id:'1',
      name: 'The Fellowship Of The Ring',
      cookTime: "445",
      price: 350,
      favorite: false,
      origins: ['J.R.R Tolkien'],
      stars: 4.5,
      imageUrl: 'https://i.postimg.cc/wvgtwsws/followship-of-ring.jpg',
      tags: ['Fiction'],
    },
    {
      id:'2',
      name: 'Wings of Fire',
      price: 500,
      cookTime: '350',
      favorite: true,
      origins: ['A. P. J. Abdul Kalam'],
      stars: 4.7,
      imageUrl: 'https://i.postimg.cc/9Qfqztjf/apj.jpg',
      tags: ['Autobiography'],
    },
    {
      id:'3',
      name: 'Anna Karenina',
      price: 297,
      cookTime: '413',
      favorite: false,
      origins: ['Leo Tolstoy'],
      stars: 3.5,
      imageUrl: 'https://i.postimg.cc/KzVtJDHv/anna-karenina.jpg',
      tags: ['Romance'],
    },
    {
      id:'4',
      name: 'Romeo and Juliet',
      price: 300,
      cookTime: '276',
      favorite: true,
      origins: ['William Shakespeare'],
      stars: 3.3,
      imageUrl: 'https://i.postimg.cc/VspFRmxB/romeo-and-juliet.jpg',
      tags: ['Romance'],
    },
    {
      id:'5',
      name: 'Dragonflight',
      price: 650,
      cookTime: '675',
      favorite: false,
      origins: ['Anne McCaffrey'],
      stars: 3.0,
      imageUrl: 'https://i.postimg.cc/JzRzVWb9/dragonflight.jpg',
      tags: ['Fiction'],
    },
    {
      id:'6',
      name: 'Mein Kampf',
      price: 287,
      cookTime: '437',
      favorite: false,
      origins: ['Adolf Hitler'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/Xqz6LbXm/hitler.jpg',
      tags: ['Autobiography'],
    },
    {
      id:'7',
      name: 'Gone with the Wind',
      price: 460,
      cookTime: '634',
      favorite: false,
      origins: ['Margaret Mitchell'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/jdFPKb63/gone-with-wind.jpg',
      tags: ['Romance'],
    },
    {
      id:'8',
      name: 'The Golden Compass',
      price: 390,
      cookTime: '167',
      favorite: false,
      origins: ['Philip Pullman'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/MHzFZtdK/golden-compass.jpg',
      tags: ['Fiction'],
    },
    {
      id:'9',
      name: 'Pride and Prejudice',
      price: 420,
      cookTime: '574',
      favorite: false,
      origins: ['Jane Austen'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/QdWwbfYV/pride-and-prejudice.jpg',
      tags: ['Romance'],
    },
    {
      id:'10',
      name: 'The Once and Future King',
      price: 250,
      cookTime: '376',
      favorite: false,
      origins: ['T. H. White'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/QtFM4kpC/the-once-and-future-king.jpg',
      tags: ['Fiction'],
    },
    {
      id:'11',
      name: 'My Experiments with Truth',
      price: 450,
      cookTime: '764',
      favorite: false,
      origins: ['Mahatma Gandhi'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/bNwvRyVC/gandhi.jpg',
      tags: ['Autobiography'],
    },
    {
      id:'12',
      name: 'Jane Eyre',
      price: 180,
      cookTime: '465',
      favorite: false,
      origins: ['Charlotte Brontë'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/BngDd0Vz/jane-eyre.jpg',
      tags: ['Romance'],
    },
    {
      id:'13',
      name: 'Becoming',
      price: 400,
      cookTime: '379',
      favorite: false,
      origins: ['Michelle Obama'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/vH04Rg6w/becoming.jpg',
      tags: ['Autobiography'],
    },
    {
      id:'14',
      name: 'The Lion, the Witch and the Wardrobe',
      price: 600,
      cookTime: '864',
      favorite: false,
      origins: ['C S. Lewis'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/sX7kgMzK/narnia.jpg',
      tags: ['Fiction'],
    },
    {
      id:'15',
      name: 'The Diary of a Young Girl',
      price: 450,
      cookTime: '369',
      favorite: false,
      origins: ['Anne Frank'],
      stars: 4.0,
      imageUrl: 'https://i.postimg.cc/cCQfMsD4/diary-of-young-girl.jpg',
      tags: ['Autobiography'],
    },
  ]

  export const sample_tags:any[] = [
    { name: 'All', count: 15 },
    { name: 'Autobiography', count: 5 },
    { name: 'Fiction', count: 5 },
    { name: 'Romance', count: 5 },
  ]

  export const sample_users: any[] = [
    {
      name: "John Doe",
      email: "john@gmail.com",
      password: "12345",
      address: "Toronto On",
      isAdmin: true,
    },
    {
      name: "Jane Doe",
      email: "jane@gmail.com",
      password: "12345",
      address: "Shanghai",
      isAdmin: false,
    },
  ];